<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class BarangSeeder extends Seeder
{
    public function run(): void
    {
        DB::table('barang')->insert([
            // TENDA (kategori_id = 1)
            [
                'kategori_id' => 1,
                'nama_barang' => 'Tenda Kapasitas 2 Orang',
                'deskripsi' => 'Tenda dome untuk 2 orang, waterproof',
                'harga_per_hari' => 25000,
                'stok' => 15,
                'kondisi' => 'Baik',
                'is_populer' => true,
                'gambar' => 'tenda-2.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kategori_id' => 1,
                'nama_barang' => 'Tenda Kapasitas 4 Orang',
                'deskripsi' => 'Tenda besar untuk 4 orang, double layer',
                'harga_per_hari' => 40000,
                'stok' => 10,
                'kondisi' => 'Baik',
                'is_populer' => true,
                'gambar' => 'tenda-4.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kategori_id' => 1,
                'nama_barang' => 'Tenda Kapasitas 6 Orang',
                'deskripsi' => 'Tenda family size, cocok untuk rombongan',
                'harga_per_hari' => 60000,
                'stok' => 5,
                'kondisi' => 'Baik',
                'is_populer' => false,
                'gambar' => 'tenda-6.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kategori_id' => 1,
                'nama_barang' => 'Fly Sheet',
                'deskripsi' => 'Terpal pelindung tambahan untuk tenda',
                'harga_per_hari' => 15000,
                'stok' => 20,
                'kondisi' => 'Baik',
                'is_populer' => false,
                'gambar' => 'flysheet.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // CARRIER (kategori_id = 2)
            [
                'kategori_id' => 2,
                'nama_barang' => 'Carrier 60L',
                'deskripsi' => 'Carrier kapasitas 60 liter, cocok untuk 2-3 hari',
                'harga_per_hari' => 30000,
                'stok' => 12,
                'kondisi' => 'Baik',
                'is_populer' => true,
                'gambar' => 'carrier-60.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kategori_id' => 2,
                'nama_barang' => 'Carrier 80L',
                'deskripsi' => 'Carrier besar 80 liter untuk perjalanan panjang',
                'harga_per_hari' => 40000,
                'stok' => 8,
                'kondisi' => 'Baik',
                'is_populer' => false,
                'gambar' => 'carrier-80.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kategori_id' => 2,
                'nama_barang' => 'Daypack 25L',
                'deskripsi' => 'Tas punggung kecil untuk day trip',
                'harga_per_hari' => 15000,
                'stok' => 20,
                'kondisi' => 'Baik',
                'is_populer' => false,
                'gambar' => 'daypack.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // SLEEPING BAG (kategori_id = 3)
            [
                'kategori_id' => 3,
                'nama_barang' => 'Sleeping Bag Biasa',
                'deskripsi' => 'Sleeping bag standar untuk suhu 10-20°C',
                'harga_per_hari' => 15000,
                'stok' => 25,
                'kondisi' => 'Baik',
                'is_populer' => true,
                'gambar' => 'sb-biasa.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kategori_id' => 3,
                'nama_barang' => 'Sleeping Bag Bulu Angsa',
                'deskripsi' => 'Sleeping bag premium untuk suhu dingin',
                'harga_per_hari' => 25000,
                'stok' => 10,
                'kondisi' => 'Baik',
                'is_populer' => true,
                'gambar' => 'sb-premium.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kategori_id' => 3,
                'nama_barang' => 'Matras Camping',
                'deskripsi' => 'Matras lipat untuk alas tidur',
                'harga_per_hari' => 10000,
                'stok' => 30,
                'kondisi' => 'Baik',
                'is_populer' => false,
                'gambar' => 'matras.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // KOMPOR & PERALATAN MASAK (kategori_id = 4)
            [
                'kategori_id' => 4,
                'nama_barang' => 'Kompor Camping',
                'deskripsi' => 'Kompor portable dengan tabung gas',
                'harga_per_hari' => 20000,
                'stok' => 15,
                'kondisi' => 'Baik',
                'is_populer' => true,
                'gambar' => 'kompor.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kategori_id' => 4,
                'nama_barang' => 'Nesting Set 4 Pax',
                'deskripsi' => 'Set peralatan masak untuk 4 orang',
                'harga_per_hari' => 25000,
                'stok' => 10,
                'kondisi' => 'Baik',
                'is_populer' => false,
                'gambar' => 'nesting.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kategori_id' => 4,
                'nama_barang' => 'Gas Kaleng 230gr',
                'deskripsi' => 'Gas untuk kompor camping',
                'harga_per_hari' => 20000,
                'stok' => 50,
                'kondisi' => 'Baru',
                'is_populer' => false,
                'gambar' => 'gas.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // LAMPU & PENERANGAN (kategori_id = 5)
            [
                'kategori_id' => 5,
                'nama_barang' => 'Lampu Emergency',
                'deskripsi' => 'Lampu darurat LED rechargeable',
                'harga_per_hari' => 10000,
                'stok' => 20,
                'kondisi' => 'Baik',
                'is_populer' => false,
                'gambar' => 'lampu-emergency.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kategori_id' => 5,
                'nama_barang' => 'Headlamp',
                'deskripsi' => 'Lampu kepala untuk trekking malam',
                'harga_per_hari' => 15000,
                'stok' => 18,
                'kondisi' => 'Baik',
                'is_populer' => true,
                'gambar' => 'headlamp.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kategori_id' => 5,
                'nama_barang' => 'Senter LED',
                'deskripsi' => 'Senter taktis LED terang',
                'harga_per_hari' => 10000,
                'stok' => 15,
                'kondisi' => 'Baik',
                'is_populer' => false,
                'gambar' => 'senter.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // PERALATAN PENDAKIAN (kategori_id = 6)
            [
                'kategori_id' => 6,
                'nama_barang' => 'Trekking Pole',
                'deskripsi' => 'Tongkat gunung adjustable',
                'harga_per_hari' => 15000,
                'stok' => 12,
                'kondisi' => 'Baik',
                'is_populer' => false,
                'gambar' => 'pole.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kategori_id' => 6,
                'nama_barang' => 'Carabiner',
                'deskripsi' => 'Carabiner untuk pengaman',
                'harga_per_hari' => 5000,
                'stok' => 30,
                'kondisi' => 'Baik',
                'is_populer' => false,
                'gambar' => 'carabiner.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kategori_id' => 6,
                'nama_barang' => 'Rain Cover',
                'deskripsi' => 'Cover anti hujan untuk carrier',
                'harga_per_hari' => 10000,
                'stok' => 25,
                'kondisi' => 'Baik',
                'is_populer' => false,
                'gambar' => 'raincover.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // PAKAIAN & ALAS KAKI (kategori_id = 7)
            [
                'kategori_id' => 7,
                'nama_barang' => 'Jaket Gunung',
                'deskripsi' => 'Jaket windproof dan waterproof',
                'harga_per_hari' => 30000,
                'stok' => 15,
                'kondisi' => 'Baik',
                'is_populer' => true,
                'gambar' => 'jaket.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kategori_id' => 7,
                'nama_barang' => 'Sepatu Tracking',
                'deskripsi' => 'Sepatu gunung anti slip',
                'harga_per_hari' => 35000,
                'stok' => 10,
                'kondisi' => 'Baik',
                'is_populer' => true,
                'gambar' => 'sepatu.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kategori_id' => 7,
                'nama_barang' => 'Poncho',
                'deskripsi' => 'Jas hujan poncho',
                'harga_per_hari' => 10000,
                'stok' => 20,
                'kondisi' => 'Baik',
                'is_populer' => false,
                'gambar' => 'poncho.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);

        echo "✅ Barang berhasil di-seed dengan " . DB::table('barang')->count() . " item!\n";
    }
}